pipeline:
  identifier: Build_MalliPermier_terraformmodule_1709828745149
  name: Build terraformmodule
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1709828696481
        repoName: MalliPermier/terraformmodule
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: Terraform init
                  spec:
                    shell: Sh
                    command: |-
                      terraform init
                      ls 
                      pwd
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: az login
                  identifier: az_login
                  spec:
                    shell: Sh
                    command: az login
              - step:
                  type: Run
                  name: Terraform plan
                  identifier: Run_3
                  spec:
                    shell: Sh
                    command: terraform plan
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        when:
          pipelineStatus: Success
    - stage:
        name: Apply Changes
        identifier: Apply_Changes
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Apply changes
                  identifier: Apply_changes
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: Deploy Infra
        identifier: Deploy_Infra
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: terraform apply --auto-approve
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
