pipeline:
  identifier: Build_MalliPermier_terraformmodule_1709828745149
  name: Build terraformmodule
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1709828696481
        repoName: MalliPermier/terraformmodule
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: |-
                      terraform init
                      ls 
                      pwd
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: az login
                  identifier: az_login
                  spec:
                    shell: Sh
                    command: az login
              - step:
                  type: Run
                  name: Run_3
                  identifier: Run_3
                  spec:
                    shell: Sh
                    command: terraform plan
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
